# Copyright (c) 2010 Martin Ueding <dev@martin-ueding.de>

.PHONY: magneticbottle.jar
magneticbottle.jar:
	javac MagnetischeFlascheSimulator.java
	jar cfm magneticbottle.jar manifest.txt *.class *.java
